# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e5241604f3f3ea4ccda0076e1a2d49854aa794a05f65f969a883d49c4894aaa43cbffbb45ae3744f39a1dcc8028f8ce65160293ef7abedc36fe467b5897d1a6

test:
  secret_key_base: e3b2067bf766ad95675c4ce07ab86314ac824d7f05ddaa37ca4e36bb1463d9748985b43151f6a5401dcb7be6f5c72dff2df04f2eb5f1d267b71cd1590f86f6d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
